In [9]:
import sys
import os

# Get project root (one level up from notebooks)
project_root = os.path.abspath("..")

# Add to path if not already there
if project_root not in sys.path:
    sys.path.insert(0, project_root)

print(project_root)

/Users/keira/code/mi-mi-mia/smart-stethoscope

In [12]:
import preprocessing
dir(preprocessing)

['BaseEstimator',
 'DataLoader',
 'FeatureConstructor',
 'FeatureEncoder',
 'Imputer',
 'LabelEncoder',
 'OneHotEncoder',
 'Path',
 'Pipeline',
 'Scaler',
 'SimpleImputer',
 'StandardScaler',
 'StratifiedShuffleSplit',
 'TransformerMixin',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'calculate_bmi',
 'extract_breathing_cycles',
 'get_breathing_cycle',
 'lb',
 'np',
 'os',
 'pd',
 'sf',
 'stratified_group_split']

In [13]:
from preprocessing import DataLoader, FeatureEncoder, FeatureConstructor

In [14]:
loader = DataLoader(
    audio_path="/Users/keira/code/mi-mi-mia/smart-stethoscope/raw_data/Respiratory_Sound_Database/Respiratory_Sound_Database/audio_and_txt_files",
    demographic_path="/Users/keira/code/mi-mi-mia/smart-stethoscope/raw_data/demographic_info.txt",
    diagnosis_path="/Users/keira/code/mi-mi-mia/smart-stethoscope/raw_data/Respiratory_Sound_Database/Respiratory_Sound_Database/patient_diagnosis.csv"
)

In [16]:
df = loader.transform(None)
df.head()

,start,end,crackles,weezels,pid,chest_location,filename,disease,age,sex,adult_bmi,child_weight,child_height
0,0.022,0.364,0,0,148,Al,148_1b1_Al_sc_Meditron,URTI,4.0,M,NaN,33.0,110.0
1,0.364,2.436,0,0,148,Al,148_1b1_Al_sc_Meditron,URTI,4.0,M,NaN,33.0,110.0
2,2.436,4.636,0,0,148,Al,148_1b1_Al_sc_Meditron,URTI,4.0,M,NaN,33.0,110.0
3,4.636,6.793,0,0,148,Al,148_1b1_Al_sc_Meditron,URTI,4.0,M,NaN,33.0,110.0
4,6.793,8.750,0,0,148,Al,148_1b1_Al_sc_Meditron,URTI,4.0,M,NaN,33.0,110.0

In [17]:
encoder = FeatureEncoder()
encoder.fit(df)
encoded_df = encoder.transform(df)

encoded_df.head()

,start,end,crackles,weezels,pid,filename,age,sex,adult_bmi,child_weight,...,disease_LRTI,disease_Pneumonia,disease_URTI,chest_location_Al,chest_location_Ar,chest_location_Ll,chest_location_Lr,chest_location_Pl,chest_location_Pr,chest_location_Tc
0,0.022,0.364,0,0,148,148_1b1_Al_sc_Meditron,4.0,1,NaN,33.0,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.364,2.436,0,0,148,148_1b1_Al_sc_Meditron,4.0,1,NaN,33.0,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2.436,4.636,0,0,148,148_1b1_Al_sc_Meditron,4.0,1,NaN,33.0,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
3,4.636,6.793,0,0,148,148_1b1_Al_sc_Meditron,4.0,1,NaN,33.0,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
4,6.793,8.750,0,0,148,148_1b1_Al_sc_Meditron,4.0,1,NaN,33.0,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

In [18]:
encoded_df.shape
encoded_df.columns

Index(['start', 'end', 'crackles', 'weezels', 'pid', 'filename', 'age', 'sex',
       'adult_bmi', 'child_weight', 'child_height', 'disease_Asthma',
       'disease_Bronchiectasis', 'disease_Bronchiolitis', 'disease_COPD',
       'disease_Healthy', 'disease_LRTI', 'disease_Pneumonia', 'disease_URTI',
       'chest_location_Al', 'chest_location_Ar', 'chest_location_Ll',
       'chest_location_Lr', 'chest_location_Pl', 'chest_location_Pr',
       'chest_location_Tc'],
      dtype='object')

In [19]:
encoded_df.columns

Index(['start', 'end', 'crackles', 'weezels', 'pid', 'filename', 'age', 'sex',
       'adult_bmi', 'child_weight', 'child_height', 'disease_Asthma',
       'disease_Bronchiectasis', 'disease_Bronchiolitis', 'disease_COPD',
       'disease_Healthy', 'disease_LRTI', 'disease_Pneumonia', 'disease_URTI',
       'chest_location_Al', 'chest_location_Ar', 'chest_location_Ll',
       'chest_location_Lr', 'chest_location_Pl', 'chest_location_Pr',
       'chest_location_Tc'],
      dtype='object')

In [20]:
constructor = FeatureConstructor()
constructor.fit(encoded_df)
final_df = constructor.transform(encoded_df)

final_df.head()

,crackles,weezels,pid,filename,age,sex,disease_Asthma,disease_Bronchiectasis,disease_Bronchiolitis,disease_COPD,...,disease_URTI,chest_location_Al,chest_location_Ar,chest_location_Ll,chest_location_Lr,chest_location_Pl,chest_location_Pr,chest_location_Tc,cycle_length,bmi
0,0,0,148,148_1b1_Al_sc_Meditron,4.0,1,0.0,0.0,0.0,0.0,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.342,1.704545
1,0,0,148,148_1b1_Al_sc_Meditron,4.0,1,0.0,0.0,0.0,0.0,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,2.072,1.704545
2,0,0,148,148_1b1_Al_sc_Meditron,4.0,1,0.0,0.0,0.0,0.0,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,2.200,1.704545
3,0,0,148,148_1b1_Al_sc_Meditron,4.0,1,0.0,0.0,0.0,0.0,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,2.157,1.704545
4,0,0,148,148_1b1_Al_sc_Meditron,4.0,1,0.0,0.0,0.0,0.0,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.957,1.704545

In [22]:
final_df.columns

Index(['crackles', 'weezels', 'pid', 'filename', 'age', 'sex',
       'disease_Asthma', 'disease_Bronchiectasis', 'disease_Bronchiolitis',
       'disease_COPD', 'disease_Healthy', 'disease_LRTI', 'disease_Pneumonia',
       'disease_URTI', 'chest_location_Al', 'chest_location_Ar',
       'chest_location_Ll', 'chest_location_Lr', 'chest_location_Pl',
       'chest_location_Pr', 'chest_location_Tc', 'cycle_length', 'bmi'],
      dtype='object')

In [23]:
final_df.dtypes

crackles                    int64
weezels                     int64
pid                         int32
filename                   object
age                       float64
sex                         int64
disease_Asthma            float64
disease_Bronchiectasis    float64
disease_Bronchiolitis     float64
disease_COPD              float64
disease_Healthy           float64
disease_LRTI              float64
disease_Pneumonia         float64
disease_URTI              float64
chest_location_Al         float64
chest_location_Ar         float64
chest_location_Ll         float64
chest_location_Lr         float64
chest_location_Pl         float64
chest_location_Pr         float64
chest_location_Tc         float64
cycle_length              float64
bmi                       float64
dtype: object